title: Ruecharli

description: Long-time worldbuilding enthusiast. My goal is to create resources for aspiring worldbuilders, specifically related to cartography, astronomy, and calendars.

theme: minima

minima:
  skin: auto
  show_excerpts: true
  hide_site_feed_link: true
  nav_pages:
    - index
    - search

author: Rue Charli (she/her)

email: "contact@ruecharli.blog"

